Bugfix/179 instance name used to find dep get it dep class
fluttercommunity/get_it pull request #181
Opened 2021-04-24 09:59 UTC by n3wtron

Created a dedicated class to manage the dependency (type + instanceName)

2021-04-24 10:02 UTC, n3wtron commented
Please note that this change is not retro compatible.
`dependsOn` attribute now need a `GetItDep` class instead of a `Type`

2021-04-25 14:19 UTC, escamoteur commented
Hmm, give me a day to ponder about that :-)

2021-04-26 06:25 UTC, n3wtron commented
Hi, probably I've found a way to make it retro-compatible. Can you check it, please?

2021-04-28 08:13 UTC, escamoteur requested changes
thanks a lot for this contribution, I added some comments

2021-04-28 08:13 UTC, escamoteur commented on lib/get_it.dart
> +class GetItDep extends Type {
I have to admit this is really a clever idea. But I would rename GetItDep to InitDependency

2021-04-28 08:13 UTC, escamoteur commented on README.md
> +To synchronize with other "async Singletons" you can pass a list of `Type`s in `dependsOn` that have to be ready before the passed factory is executed.
Could you please add a paragraph year that explains what to pass as type in case you want to address an instance that is registered with name

2021-04-28 08:13 UTC, escamoteur commented on test/async_test.dart
> +    }, dependsOn: [TestClass]);
please add a separate test that uses the wrapper class to define the dependencies

2021-04-28 12:45 UTC, n3wtron commented on README.md
> +To synchronize with other "async Singletons" you can pass a list of `Type`s in `dependsOn` that have to be ready before the passed factory is executed.
Absolutely

2021-04-28 12:49 UTC, n3wtron commented on test/async_test.dart
> +    }, dependsOn: [TestClass]);
like this?
https://github.com/fluttercommunity/get_it/pull/181/files#diff-295c09a4325cfd060c5ab0c0264e7da5384ac996145bcc0c4b99b593bc615386R677

2021-04-28 14:50 UTC, escamoteur commented on test/async_test.dart
> +    }, dependsOn: [TestClass]);
yep

2021-04-30 06:27 UTC, escamoteur commented on README.md
> -  getIt.registerSingletonAsync<RestService>(() async => RestService2().init(), instanceName : "restService2");
Why did you remove the init()?

2021-04-30 06:27 UTC, escamoteur commented on README.md
> +To synchronize with other "async Singletons" you can pass a list of `Type`s in `dependsOn` that have to be ready before the passed factory is executed.
I mean it still does not describe how to do it if you have a named instance :-)

2021-04-30 06:36 UTC, n3wtron commented on README.md
> -  getIt.registerSingletonAsync<RestService>(() async => RestService2().init(), instanceName : "restService2");
Hi, is necessary for this example? if I understood properly the `init` method is to "simulate" an operation that takes time, but in this case, I don't think is needed.
Anyway, I can add it again if you want.

2021-04-30 06:40 UTC, escamoteur commented on README.md
> -  getIt.registerSingletonAsync<RestService>(() async => RestService2().init(), instanceName : "restService2");
No, it is used because any asnycRegistration expects an async factory function which your solution is because is uses the `async` keyword, but there is no such thing as an async class constructor that's why it would be a bad example.
the init function to be used like that has to return `this` to be usable like that

2021-04-30 06:42 UTC, n3wtron commented on README.md
> -  getIt.registerSingletonAsync<RestService>(() async => RestService2().init(), instanceName : "restService2");
I will fix it

2021-04-30 06:47 UTC, n3wtron commented on README.md
> -  getIt.registerSingletonAsync<RestService>(() async => RestService2().init(), instanceName : "restService2");
https://github.com/fluttercommunity/get_it/pull/181/commits/c090988bc9415fb4babd24f2f8db18f90c024ad4

2021-05-01 12:26 UTC, escamoteur commented
In the readme we currently have:

### Automatic using `dependsOn`
In case that this services have to be initialized in a certain order because they depend on that other services are already ready to be used you can use the `dependsOn` parameter of `registerFactoryAsync`. If you have a non async Singleton that depends on other Singletons, there is `registerSingletonWithDependencies`. In the following example, `DbService` depends on `ConfigService`, and `AppModel` depends on `ConfigService` and `RestService`
```Dart
  getIt.registerSingletonAsync<ConfigService>(() async {
    final configService = ConfigService();
    await configService.init();
    return configService;
  });
  getIt.registerSingletonAsync<RestService>(() async => RestService().init());
  getIt.registerSingletonAsync<DbService>(createDbServiceAsync,
      dependsOn: [ConfigService]);
  getIt.registerSingletonWithDependencies<AppModel>(
      () => AppModelImplmentation(),
      dependsOn: [ConfigService, DbService, RestService]);
```
When using `dependsOn` you ensure that the registration waits with creating its singleton on the completion of the type defined in `dependsOn`.


could you add there how to use the new `InitDependency` ?

2021-05-01 17:14 UTC, escamoteur approved these changes

2021-05-01 17:15 UTC, escamoteur commented
I don't know if you follow me on Twitter but I just tweeted some thoughts of new functionality for get_it:
https://twitter.com/ThomasBurkhartB/status/1388539107756883971?s=20
What do you think?

2021-05-01 17:17 UTC, escamoteur approved these changes
Awesome, thanks a lot!!!

2021-05-01 17:17 UTC, merged

2021-05-01 17:18 UTC, n3wtron commented
Thanks to you @escamoteur your job with this lib is awesome.

2021-05-01 17:19 UTC, escamoteur commented
Have you tried the get_it_mixin?

2021-05-01 17:23 UTC, n3wtron commented
No, I didn't.
I will take a look and try it.
thank you