Added documentation for getAll
fluttercommunity/get_it pull request #363
Opened 2024-04-17 14:53 UTC by hughesjs

2024-04-18 08:22 UTC, escamoteur requested changes
Thanks, please add two small things

2024-04-18 08:22 UTC, escamoteur commented on README.md
> +> To avoid this being a breaking change, this is an optional feature, to enable this you need to call:
I would add: and to avoid accidentally registering a type twice which might be a mistake for the majority use-cases unless you need this specific ability.

2024-04-18 08:22 UTC, escamoteur commented on README.md
> +
this will return all registered instances of this interface with or without an instance name. 

(or something similar if you have a better phrasing

2024-04-20 13:42 UTC, hughesjs commented
Made the requested changes :)

2024-04-22 08:12 UTC, escamoteur approved these changes
thanks a lot. Your English is definitely better than mine :-)

2024-04-22 08:12 UTC, merged

2024-04-22 21:53 UTC, hughesjs commented
No worries, can we close #75 now?

2024-04-23 05:08 UTC, escamoteur commented
I still haven't added the allScopes parameter
Am 22. Apr. 2024, 23:53 +0200 schrieb James H ***@***.***>:
> No worries, can we close #75 now?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>