Implement new methods for GetIt service locator
fluttercommunity/get_it pull request #383
Opened 2024-10-23 12:54 UTC by IvanGael

- **Access Count Tracking** : We can now track how many times a singleton has been accessed using the `getAccessCount` method.
- **Clear All Instances** : The `clearAllInstances` method allows clearing all instances of a specific type, including named instances.
- **Set Default Instance** : The `setDefault` method allows setting or replacing the default instance for a type, with an option to use a named instance.

2024-10-23 13:06 UTC, escamoteur commented
HI, I'm in general happy about contributions to get_it but before submitting an PR with new functions it would be good to open an issue outlining the purpose of the new functions.

* I can see some value to get the accessnumber for a certain type while debugging. does it have any meaningful application in an production app? 
* clearAll instances: this would be better implemented by extending the `unregister` function with an `fromAllScopes` parameter
* setDefaultInstance: this is misleading because in reality it only replaces an instance and it only works for singletons. So it would probably better be named as `replaceSingletonInstance`

cheers 
Thomas

2024-10-23 13:21 UTC, IvanGael commented
@escamoteur  Ah sorry, I had to open an issue and make the proposal first before submitting my PR 🙂.

I will make some adjustments regarding your suggestions.

2024-10-23 15:06 UTC, IvanGael commented
I've made some adjustments:

- **Access count**: You're right that the access count might not have significant value in a production app. I've kept it, but mark it as a debug-only feature.
- **Clearing all instances**: Extending the `unregister` function with a `fromAllScopes` parameter is a more flexible and consistent approach.
- **Renaming `setDefault` to `replaceSingletonInstance`**: The name `replaceSingletonInstance` more accurately describes what the function does.

2024-10-23 15:12 UTC, escamoteur commented
It might be a good idea to wrap the code that updates the count inside an assert so it will be removed in a production app
Am 23. Okt. 2024, 16:07 +0100 schrieb Ivan APEDO ***@***.***>:
> I've made some adjustments:
>
> • Access count: You're right that the access count might not have significant value in a production app. I've kept it, but mark it as a debug-only feature.
> • Clearing all instances: Extending the unregister function with a fromAllScopes parameter is a more flexible and consistent approach.
> • Renaming setDefault to replaceSingletonInstance: The name replaceSingletonInstance more accurately describes what the function does.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-23 19:29 UTC, IvanGael commented
@escamoteur I check here the debug mode before updating the count. Should I put this logic inside the assert ?

![image](https://github.com/user-attachments/assets/d4f41dd8-f85f-44a2-8654-9f5ed01fae9d)

2024-10-23 22:17 UTC, escamoteur commented
Checking for debug mode will execute that check on every call in release. So wrapping the increment inside an asserts bool test condition (make the increment a function that returns true) will completely remove it in release builds
Am 23. Okt. 2024, 20:30 +0100 schrieb Ivan APEDO ***@***.***>:
> @escamoteur I check here the debug mode before updating the count. Should I put this logic inside the assert ?
> image.png (view on web)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-24 09:00 UTC, escamoteur requested changes

2024-10-24 09:00 UTC, escamoteur commented on lib/get_it.dart
> +  FutureOr unregisterFromScopes<T extends Object>({
I meant to add a bool parameter `fromAllScopes` to the existing unregister function

2024-10-24 09:00 UTC, escamoteur commented on lib/get_it_impl.dart
> +    assert(() {
this doesn't make sense. this assert will get removed in release mode. you can check `kReleaseMode ` and throw a Stateerror if the function is called in release mode. 
Or you could do the call to _findFactory inside the assert and assign the value to a local variable declared before the assert that is initialized with -1 that is returned at the end of the function

2024-10-24 09:00 UTC, escamoteur commented on lib/get_it_impl.dart
> +    } else {
I think you don't need this f you use `_findFirstFactoryByNameAndType` which will throw the correct exception already

2024-10-24 09:00 UTC, escamoteur commented on lib/get_it_impl.dart
> +      if (existingFactory.factoryType == _ServiceFactoryType.constant) {
it should also be possible for lazySingletons I think

2024-10-27 14:06 UTC, escamoteur commented
don't know why but your latest commit seems to touch a lot of lines which makes it difficult to follow what you changed. And idea why this is?

2024-10-27 14:31 UTC, IvanGael commented
Only the get_it.dart, get_it_impl.dart and get_it_test.dart files were modified. I did not touch any other files.

2024-10-27 14:36 UTC, escamoteur commented
Yes, but if you look at the diff of the implementation.dart it's really a lot of changes. Will need more time to carefully review them
Am 27. Okt. 2024, 14:31 +0000 schrieb Ivan APEDO ***@***.***>:
> Only the get_it.dart, get_it_impl.dart and get_it_test.dart files were modified. I did not touch any other files.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-28 09:32 UTC, IvanGael commented
I didn't change much. I just modified the new methods that I implemented myself and added a new parameter to the unregister method.

2024-10-28 10:53 UTC, escamoteur requested changes

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it.dart
> +  /// Returns true if the app is running in debug mode
what is this for?

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it.dart
> +  int getAccessCount<T extends Object>({String? instanceName});
it might make sense to also add a `resetAccessCount` if you wan to observe  the behavior only in a certain area of the app

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> +  @override
not needed

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> +  _ServiceFactory? _findFactoryByInstanceOrNull(Object instance) {
why is this added here? did you move it?

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> -  /// Unregister an instance of an object or a factory/singleton by Type [T] or by name [instanceName]
why did you delete the comments?

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> +      for (final scope in _scopes.reversed) {
this can be just the loop and after the first call to _unregisterFromScope you check for !fromAllScopes you do a break

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> +    if (factoryToRemove == null) {
that is a problem, because if you don't select allScopes you want to throw here.
Therefore I would inline the code of that function int the loop above then you have access  to the `allScopes` parameter and you can throw if you haven't found a registration in any scope

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> +    if (!ignoreReferenceCount && factoryToRemove._referenceCount > 0) {
good catch, I hadn't used the ignoreReferenceCount

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> -      factoryToRemove.registrationScope.typeRegistrations.remove(T);
actually there is a problem in your logic. the _findByTypeAndName searches already through all scopes, so you might get a registration from a lower scope. So instead of looping over all scopes, you probably have to repeatedly call unregister and check if either the scope of the registration is the base scope or if its not longer found,

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> -    throwIf(
why?

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> +    final registeredFactory = _findFactoryByInstanceOrNull(instance);
why?

2024-10-28 10:53 UTC, escamoteur commented on lib/get_it_impl.dart
> +    if (!_isDebugMode) {
where do you get _isDebugMode from? As get_it should not depend on Flutter so you should to

```
bool isDebug = false;
assert(() {
  isDebug= true;
  return true;
}());

2024-11-03 17:22 UTC, IvanGael commented on lib/get_it.dart
> +  /// Returns true if the app is running in debug mode
To check allowReassignment

2024-11-03 17:31 UTC, IvanGael commented on lib/get_it_impl.dart
> +  _ServiceFactory? _findFactoryByInstanceOrNull(Object instance) {
No I don't touch it!

2024-11-03 17:31 UTC, IvanGael commented on lib/get_it_impl.dart
> -  /// Unregister an instance of an object or a factory/singleton by Type [T] or by name [instanceName]
I didn't delete comment here

2024-11-03 17:37 UTC, IvanGael commented on lib/get_it_impl.dart
> -    throwIf(
needed

2024-11-03 17:37 UTC, IvanGael commented on lib/get_it_impl.dart
> +    final registeredFactory = _findFactoryByInstanceOrNull(instance);
Need to check this

2024-11-06 17:50 UTC, escamoteur commented
Sorry Ivan, I was super busy these days
Nachricht von Ivan APEDO ***@***.***> am Nov 6, 2024, 6:45 PM +0100:
> @IvanGael requested your review on: #383 Implement new methods for GetIt service locator.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.Message ID: ***@***.***>

2024-11-17 11:31 UTC, merged

2024-11-17 11:32 UTC, escamoteur commented
will do some final fixes

2024-11-17 12:31 UTC, escamoteur commented
please check my changes in https://github.com/fluttercommunity/get_it/tree/incoming
I think this is an easier way to implement the unregister fromAllScopes