Revise and improve cached factory handling with params
fluttercommunity/get_it pull request #387
Opened 2024-10-25 08:41 UTC by ArtAhmetajCR

This Pr references issue #382 where an assertion  on the getObject method (and its async equivalent) blocks cached factories from having parameters passed.
The fix is adjusting the assertion to include the "cachedFactory" as a type.
While fixing this issue I also noticed that the lastParameters were not being saved in the cached factory section, which resulted in the cached factory functions being broken since this check always failed:
```dart
if (weakReferenceInstance?.target != null &&
              param1 == lastParam1 &&
              param2 == lastParam2)
```
Saving the lastParams when creating new instances fixes this.

Appropriate tests have been writen for the cached factory which were entirely missing earlier.

2024-10-25 08:44 UTC, samirsimnica approved these changes
LGTM!

2024-10-27 13:56 UTC, escamoteur commented
@samirsimnica just curious, why could you approve this PR?

2024-10-27 14:02 UTC, escamoteur commented on lib/get_it_impl.dart
> +    P1? param1,
why does the _register function needs param1 and param2?

2024-10-28 08:12 UTC, ArtAhmetajCR commented on lib/get_it_impl.dart
> +    P1? param1,
It was an oversight on my side, I saw later on that params need only be passed on get object to create new instance, or return the cached one. They have been removed in a new commit.

2024-10-28 09:29 UTC, escamoteur approved these changes

2024-10-28 09:41 UTC, escamoteur requested changes

2024-10-28 09:41 UTC, escamoteur commented on test/get_it_test.dart
> +  void dispose() {
I think you don't use the `dispose` in your test so the linter complains and the CI can't run.

2024-10-28 11:10 UTC, ArtAhmetajCR commented on test/get_it_test.dart
> +  void dispose() {
I have removed the method given that its not used on the test class atm, added it for consistency since it was on other classes but I dont use dispose counter to assert anything atm, if you want I can add it with your guidance.

2024-10-28 11:22 UTC, merged